### ISSUE TITLE
Mise en place de l'architecture  

### ISSUE THREAD

**Issue by moustaphadiakhate** [diikaane/Boutique2.0#1]
nous devons un premier temps initialiser le repository et écrire un document README me pour faciliter la configuration de l'environnement de développement à son nouveau développeur.
J'aurais préféré qu'on initialise l'archicheture de la sorte: 
./app/db/
./app/api
./app/model
Dans /model le UserSchemas.js
Dans /db la connexion au db.js
Dans /api le ficher users.js (crud) requests

**Comment by diikaane** [comment]
ok je suis entrain de mettre a jour le project

**Comment by moustaphadiakhate** [comment]
okay fait !
